# Generated by Django 5.1.6 on 2025-02-21 10:52

import django.db.models.deletion
import shorturls.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=511, verbose_name='Content')),
                ('type', models.CharField(choices=[('EQ', 'Equal'), ('CO', 'Contain'), ('ST', 'Start with'), ('EN', 'End with'), ('RE', 'Regular expression'), ('UR', 'URL')], default='EQ', max_length=2, verbose_name='Type')),
                ('ignore_case', models.BooleanField(default=True, verbose_name='Ignore case')),
                ('is_positive', models.BooleanField(default=False, verbose_name='Is positive')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=63)),
                ('short', models.CharField(max_length=31)),
                ('long_url', models.URLField(max_length=2047, validators=[shorturls.validators.validate_filter_long_url])),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='domains.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('domain', 'short'), name='unique_domain_short')],
            },
        ),
    ]
