services:
  api:
    image: python:3.12
    environment:
      - APPLICATION_TYPE=API
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: [ "/bin/bash", "./workflows/run-api.sh" ]
  batch:
    image: python:3.12
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings.prod
      - APPLICATION_TYPE=BATCH
    volumes:
      - .:/app
    working_dir: /app
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: [ "/bin/bash", "./workflows/run-batch.sh" ]
