services:
  app:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: [ "/bin/bash", "./workflows/run.sh" ]

  web:
    image: nginx
    volumes:
      - ./docker/nginx/sites-enabled/subshorts.com.conf:/etc/nginx/conf.d/subshorts.com.conf
      - ./docker/nginx/ssl:/root/ssl
      - ./docker/nginx/static:/home/nginx/static
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway