services:
  api:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: [ "/bin/bash", "./workflows/run.sh" ]
