services:
  app:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: [ "/bin/bash", "./docker/app.sh" ]

  web:
    image: nginx
    volumes:
      - ./docker/web.conf:/etc/nginx/conf.d/web.conf
      - ~/ssl:/ssl
      - ./static:/app/static
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway