[project]
name = "flare"
version = "0.1.0"
description = "Free subdomains and short URLs"
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
authors = [
    { name = "Seokjin Yoon" },
]
dependencies = [
    "Django==6.0.7",
    "django-apscheduler==0.7.0",
    "django-bootstrap5==26.2",
    "django-cors-headers==4.9.0",
    "django-dotenv==1.4.2",
    "djangorestframework==3.17.1",
    "djangorestframework-simplejwt==5.5.1",
    "dnslib==0.9.26",
    "drf-nested-routers==0.95.3",
    "drf-yasg==1.21.15",
    "geoip2==5.3.0",
    "requests==2.34.2",
    "social-auth-core==5.0.2",
    "social-auth-app-django==6.0.1",
    "setuptools==83.0.0",
]

[project.optional-dependencies]
dev = [
    "responses==0.26.2",
]
prod = [
    "gunicorn==26.0.0",
    "mysqlclient==2.2.8",
    "redis==8.1.0",
]

[project.urls]
Repository = "https://github.com/sjy5386/flare"

[build-system]
requires = ["setuptools>=77.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
