# Generated by Django 5.1.6 on 2025-02-21 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('your_name', models.CharField(max_length=63)),
                ('your_email', models.EmailField(max_length=254)),
                ('abusive_subdomain_name_or_short_url', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=63)),
                ('body', models.TextField()),
            ],
        ),
    ]
