# Generated by Django 5.1.6 on 2025-02-21 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=63, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='WebForwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('destination_url', models.URLField(verbose_name='Destination URL')),
                ('http_status_code', models.IntegerField(choices=[(301, 'Moved Permanently'), (302, 'Found')], verbose_name='HTTP Status Code')),
                ('force_path_root', models.BooleanField(verbose_name='Force path root?')),
            ],
        ),
    ]
